os:
  - osx

osx_image: xcode11.2

before_install:
  - brew update # To avoid SHA-256 checksum errors for example.
  - brew cask install homebrew/cask-versions/adoptopenjdk8
  - export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
  - brew cask install google-chrome # Required to run JS tests. Remove when https://youtrack.jetbrains.com/issue/KT-32075 ships.

before_script:
  - ./gradlew clean generateTests
  - if [ ! -z "$(git status --porcelain)" ]; then git diff; echo -e "\nTest files changed. Did you run ./gradlew generateTests?"; exit 1; fi

script:
  - ./gradlew -p wire-library build
  - ./gradlew build

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "a8dMh0gnfufZ4CBmqdrDqu33Gp6NoF6AgGP5joKAecHpG7wA1w9Jh/8JfHHjM6y5YZyBusSl2NPp8wkIhZsqHydgWPhwHJICuktfWB/WH/G7QW9HNM74jNODDSN5Hv5BGAc3niY+NCSKsadtD0ncXm0OxnbBmaxAPzcOH30I6I4="
    - secure: "CHuskaVfG2/oZwpns+7+Ei51RS6/nZpywmwrgo7V6Fh0uv1uobQ4oRcJ7hlKMbeH/ZDC8rmNAgpLn1untzw9M5HgKEQo/KPrZMnzy2237ru+OGham73FKiUgb3v28357igKDudNv0bnZKtJRfiGPgwZp0X2Gizk93Mx06ewZDPs="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native/
    - $HOME/.gradle/daemon/native/
